version: '3.9'

services:
  image:
    container_name: hyperf
    image: hyperf
    build:
      context: .
      args:
        APP_STAGE: dev

  bin: &base
    container_name: bin.hyperf
    profiles: ['bin']
    image: hyperf
    depends_on:
      - image
    entrypoint: ['php', bin/hyperf.php]
    env_file:
      - .env
    volumes:
      - ./:/opt/www
  
  composer: 
    <<: *base
    container_name: composer.hyperf
    profiles: ["composer"]
    entrypoint: ["composer"]
    command: validate

  app:
    container_name: app.hyperf
    profiles: []
    entrypoint:
      - php
      - bin/hyperf.php
      - server:watch

    image: hyperf
    depends_on:
      - image
    env_file:
    - .env
    volumes:
    - ./:/opt/www
    ports:
    - 9501:9501

  db:
    container_name: hyperf-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: hyperf
      MYSQL_DATABASE: hyperf
    ports:
    - 3306:3306
    volumes:
    - mysql.hyperf.dev:/var/lib/mysql

volumes:
  mysql.hyperf.dev:
    driver: local